### ISSUE TITLE
Encrypt/dencrypt with key?

### ISSUE THREAD

**Issue by imKota** [shanet/Crypto-Example#4]
Please add encrypting and dencrypt with key.
example:

Message to AES encrypt: encrypted sring
Key for encrypt: md5/sha1/another key type
Encrypted message: E+ERlsT/PQqItz71GcdFjU/nbWjELuKs4BbSVpqXLsk=
Key for decrypt: md5/sha1/another key type
Decrypted message: encrypted sring

Message to RSA encrypt: encrypted sring
Key for encrypt: md5/sha1/another key type
Encrypted message: i9ex4bu07siHvZZKCUzuQCH7AEdRKRhOjq6z+9HhWuY=
Key for decrypt: md5/sha1/another key type
Decrypted message: encrypted sring

**Comment by shanet** [comment]
I'm not sure what you mean by "md5/sha1/another key type." MD5 and SHA1 are not key types, they are (insecure) hash functions.

**Comment by imKota** [comment]
This exemple ))
